ror/turajol/config/routes.rb
Rails.application.routes.draw do

  root 'points#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :points, :only => [:index, :new, :create]
      get 'points/:id/confirm', to: 'points#confirm', as: 'point_confirm'

      post 'users/start_registration', to: 'users#start_registration', as: 'start_registration_user'
      post 'users/confirm', to: 'users#confirm', as: 'phone_confirm'
    end
  end

  namespace :admin do
    resources :points, :only => [:index, :new, :create, :destroy]
    get 'points/:id/confirm', to: 'points#confirm', as: 'point_confirm'

    get 'users', to: 'users#index', as: 'users'
    post 'users/activate', to: 'users#activate', as: 'activate'
  end
end

ror/turajol/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ror/turajol/app/models/point.rb
class Point < ApplicationRecord
  FORMAT_COORDINATES = /\A[\d]{2}[\.][\d]*\z/
  MESSAGE_ERORR_FORMAT = I18n.t(:point_format_error)

  validates :latitude, presence: true
  validates :longitude, presence: true

  validates :latitude, format: {with: FORMAT_COORDINATES, message: MESSAGE_ERORR_FORMAT}
  validates :longitude, format: {with: FORMAT_COORDINATES, message: MESSAGE_ERORR_FORMAT}

  scope :active, -> { where(deleted_at: nil) }

  def increase_counter
    self[:counter] += 1 if self[:deleted_at].nil?
  end
end

ror/turajol/app/models/user.rb
class User < ApplicationRecord
  PHONE_FORMAT = /\A\d{9}\z/
  MESSAGE_ERORR_FORMAT = I18n.t(:phone_format_error)

  validates :phone, presence: true, format: {with: PHONE_FORMAT, message: MESSAGE_ERORR_FORMAT}

  before_create :set_verification_code

  def confirm_phone(verification_code)
    if self.verification_code == verification_code
      self.code_confirmed_at = Time.now
      set_token
      save
    end
  end

  private
  def set_verification_code
    return if verification_code.present?
    self.verification_code = generate_verification_code
  end

  def generate_verification_code
    '%04d' % SecureRandom.random_number(10000)
  end

  def set_token
    self.token = generate_auth_token
    five_years = 60 * 60 * 24 * 5
    self.token_expired_at = Time.now + five_years
  end

  def generate_auth_token
    SecureRandom.uuid.gsub(/\-/, '')
  end
end

ror/turajol/app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    NAME = ENV.fetch("LOGIN"){"admin"}
    PASSWORD = ENV.fetch("PASSWORD"){"admin"}

    protect_from_forgery with: :exception
    http_basic_authenticate_with name: NAME, password: PASSWORD

    add_flash_types :error, :success
  end
end

ror/turajol/app/controllers/admin/points_controller.rb
module Admin
  class PointsController < AdminController
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    def index
      @points = Point.active
    end

    def new
      @point = Point.new
    end

    def create
      @point = Point.create(point_params)
      if @point.save
        flash[:success] = t(:point_add)
        redirect_to root_path
      else
        flash[:error] = t(:point_add_error)
        render action: :new
      end
    end

    def confirm
      @point = Point.find(params[:id])
      @point.increase_counter
      if @point.save
        flash[:success] = t(:point_confirm)
        redirect_to root_path
      else
        flash[:error] = t(:point_confirm_error)
        redirect_to root_path
      end
    end

    def destroy
      @point = Point.find(params[:id])
      @point.deleted_at = Time.now
      if @point.save
        flash[:notice] = t(:point_destroy)
        redirect_to root_path
      else
        flash[:error] = t(:point_destroy_error)
        redirect_to root_path
      end
    end

    private

    def point_params
      params.require(:point).permit(:latitude, :longitude)
    end

    def not_found
      render allert: t(:point_find_error, point_id: params[:id])
    end

  end
end

ror/turajol/app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController
    def index
      @users = User.all
    end

    def activate
      user = User.where(params[:phone]).first
      if user.confirm_phone(params[:verification_code])
        flash[:notice] = "Пользователь #{user.phone} активирован"
        redirect_to admin_users_url
      else
        flash[:error] = 'Не удалось зарегестрироваться'
        redirect_to admin_users_url
      end
    end

    def user_params
      params.require(:user).permit(:phone, :verification_code_digest)
    end
  end
end

ror/turajol/app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
    before_action :authenticate

    def authenticate
      authenticate_token || render_unauthorized
    end

    def authenticate_token
      authenticate_with_http_token do |token, options|
        User.where(token: token).first
      end
    end

    def render_unauthorized
      self.headers['WWW-Authenticate'] = 'Token realm="Application"'
      render json: {message: t(:auth_error)}, status: 401
    end
  end
end

ror/turajol/app/controllers/api/v1/points_controller.rb
module Api::V1
  class PointsController < ::Api::ApiController
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    def index
      points = Point.active
      render json: points, status: :ok
    end

    def new
      @point = Point.new
    end

    def create
      point = Point.create(point_params)
      if @point.save
        render json: Point.active, status: :created
      else
        render json: point.errors, status: 400
      end
    end

    def confirm
      point ||= Point.find(params[:id])
      point.increase_counter
      if point.save
        render json: Point.active, status: :created
      else
        render json: point.errors, status: 404
      end
    end

    private

    def point_params
      params.require(:point).permit(:latitude, :longitude)
    end

    def not_found
      render json: { message: t(:point_find_error, point_id: params[:id]) }, status: 404
    end
  end
end

ror/turajol/app/controllers/api/v1/users_controller.rb
module Api::V1
  class UsersController < ::Api::ApiController
    skip_before_action :authenticate

    def start_registration
      user = User.new(user_params)
      if user.save
        send_verification_code(user)
        render json: {message: t(:phone_confirm)}, status: :ok
      else
        render json: user.errors, status: 400
      end
    end

    def confirm
      user ||= User.where(phone: user_params[:phone]).first
      return render json: {message: t(:incorrect_phone)}, status: 404 if user.blank?

      if user.confirm_phone(user_params[:verification_code])
        render json: {auth_token: user.token}, status: :ok
      else
        render json: {message: t(:incorrect_verification_code)}, status: 404
      end
    end

    def send_verification_code(user)
      puts user.verification_code
    end

    def user_params
      params.require(:user).permit(:phone, :verification_code)
    end
  end
end

ror/turajol/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

ror/turajol/app/controllers/points_controller.rb
class PointsController < WebController
  def index
    @points = Point.active
  end
end

ror/turajol/app/controllers/web_controller.rb
class WebController < ApplicationController
  protect_from_forgery with: :exception
end

ror/turajol/app/helpers/application_helper.rb
module ApplicationHelper
end

ror/turajol/app/helpers/points_helper.rb
module PointsHelper
end

ror/turajol/app/helpers/users_helper.rb
module UsersHelper
end

ror/turajol/app/views/admin/points/index.html.erb
<div>
  <% @points.each do |point| %>
      <p>
        <%= "Широта: #{point.latitude}" %>
        <%= "Долгота: #{point.longitude}" %>
        <%= link_to "Число подтверждений: #{point.counter}", admin_point_confirm_path(point) %>
        <%= link_to "Удалить точку", admin_point_path(point), method: :delete  %>
      </p>
  <% end %>
</div>
<div>
  <%=	link_to "Добавить точку", new_admin_point_path  %>
</div>

ror/turajol/app/views/admin/points/new.html.erb
<h1> New Point</h1>

<%= form_for [:admin,@point] do |f| %>
  <p>
    <%=	f.label :latitude, "Широта" %>
    <%= f.text_field :latitude %>
  </p>
  <p>
    <%=	f.label :longitude, "Долгота" %>
    <%= f.text_field :longitude  %>
  </p>
  <p><%= f.submit "Создать точку" %></p>
<% end %>
<div>
  <%=	link_to "Вернуться назад", root_path  %>
</div>

ror/turajol/app/views/admin/users/index.html.erb
<h2>Ручная активация пользователей</h2>

<table class="table table-striped table-bordered " >
  <tr>
    <th>Номер телефон</th>
    <th>Код подтверждения</th>
    <th>Дата активации</th>
    <th>Действие</th>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td><%= user.phone  %></td>
        <td><%= user.verification_code  %></td>
        <td><%= user.code_confirmed_at %></td>
        <td>
          <%= button_to 'Активировать', admin_activate_path(phone: user.phone, verification_code: user.verification_code), method: :post%>
        </td>
      </tr>
  <% end %>
</table>

ror/turajol/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turajol</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% unless flash.empty? %>
    <% flash.each do |type, message| %>
      <div class="<%= type %>"><%= message %></div>
    <% end %>
  <% end %>
    <%= yield %>
  </body>
</html>

ror/turajol/app/views/points/index.html.erb
<div>
  <% @points.each do |point| %>
      <p>
        <%= "Широта: #{point.latitude}" %>
        <%= "Долгота: #{point.longitude}" %>
      </p>
  <% end %>
</div>

ror/turajol/app/views/points/new.html.erb
<h1> New Point</h1>

<%= form_for @point do |f| %>
  <p>
    <%=	f.label :latitude, "Широта" %>
    <%= f.text_field :latitude %>
  </p>
  <p>
    <%=	f.label :longitude, "Долгота" %>
    <%= f.text_field :longitude  %>
  </p>
  <p><%= f.submit "Создать точку" %></p>
<% end %>
<div>
  <%=	link_to "Вернуться назад", root_path  %>
</div>